### ISSUE TITLE
Residential results analysis

### ISSUE THREAD

**Issue by jayomacg** [MaREI-EPMG/times-ireland-model#25]
The current residential results allow for biofuels, but there is an issue with solar not coming through. It might be due to new timeslices?
The residential thermal retrofits are now down as the biofuels are preferred in the residential sector over thermal retrofit plus electrical heat pump.

**Comment by olejandro** [comment]
@jayomacg is it also true for the current model version? E.g. one can see most recent result [here](https://epmg.netlify.app/tim-gas-study-2022/results/residential/overview).
