### ISSUE TITLE
Bioenergy supply 

### ISSUE THREAD

**Issue by daly-h** [MaREI-EPMG/times-ireland-model#49]
Bioenergy supply is not credible in several ways. Immediate increase of ethanol in 2023 from grass is not plausible - I suggest removing the technology entirely. Similar issue with biodiesel from woody biomass. I suggest removing these technologies and just fixing domestically-produced biodiesel, ethanol and biogas supply from the findings of the SEAI heat study: https://www.seai.ie/data-and-insights/national-heat-study/sustainable-bioenergy-for/

**Comment by daly-h** [comment]
Also need to analyse whether indigenous bioenergy supply is consistent with sustainable supply of resources, from the SEAI heat study, and what consequences for land use nationally is required.

**Comment by BakytzhanSuleimenov** [comment]
Bioenergy potentials updated by @vahid-aryanpur
